### ISSUE TITLE
Results on Vid4

### ISSUE THREAD

**Issue by yuangan** [amanchadha/iSeeBetter#5]
Hi, I've tested your model weights/netG_epoch_4_1.pth, and I can't get the result of 26.57/0.773  on Foliage datasets. I just got Avg PSNR Predicted =  25.728. Could you tell me how to get it? Besides, the result of City is also under 26. These are my arguments:
`Namespace(chop_forward=False, data_dir='./Vid4', debug=False, file_list='city_test.txt', future_frame=True, gpu_mode=False, gpus=1, model='weights/netG_epoch_4_1.pth', model_type='RBPN', nFrames=7, other_dataset=True, output='Results/', residual=False, seed=123, testBatchSize=1, threads=1, upscale_factor=4)`

PS: Could you offer the augmented dataset? Thanks very much!

**Comment by amanchadha** [comment]
Hey!

Sorry for the delayed response. From your parameters, it looks like a couple of things are off:
- `city_test.txt` only has 2 images and was originally meant to pipe-clean the script infrastructure and not to compare results. You will need the full "City" imagelist to obtain a decent result. Also, note that the amount of images that `city_test.txt` uses is much lesser than the nFrames in this case, which won't let the model extract temporal information from adjacent frames since the frames aren't available.
- `nFrames` is pretty low in your case (7) and should be usually set higher.
- `other_dataset` and `residual` might also be off -- I'll need some time to look into those though.
- Lastly, I would also confirm if you're running the right library versions as mentioned in the project readme.

Hope this helps!
